
if [[ "$OS_TYPE" =~ ^freebsd || "$OS_TYPE" =~ ^bsd ]]; then
	export CLICOLOR=1
	export LSCOLORS="exfxcxdxbxegedabagacad"

	alias ls='ls -aFG'
	alias dir='ls -aFGhl'

	alias less='less -AFgJMQswX --use-color'
	export MANCOLOR=1
	export MANPAGER='less -RAFgJMQswX --use-color'

	alias open="xdg-open"
fi


if [[ "$OS_TYPE" =~ ^linux ]]; then
	alias ls='command ls -Fa --color=always'
	alias dir='command ls -Fal --color=always'
	
	alias pbcopy='xsel --clipboard --input'
	alias pbpaste='xsel --clipboard --output'

	# less version 551: 11 june 2019
	# mark nudelman, less@gnu.org
	
	alias less='less -AFgJMQswX --use-color'
	export MANCOLOR=1
	export MANPAGER='less -RAFgJMQswX --use-color'

	alias open="xdg-open"
	alias flush='sudo /etc/init.d/nscd restart'
fi

# If using Darwin, alias `md5sum` to `md5`, since none is offered by the OS
if [[ "$OS_TYPE" =~ ^darwin ]]; then
	alias ls='command ls -aFG'
	alias dir='command ls -aFGhl'

	alias md5sum="md5"

	alias flush='dscacheutil -flushcache'

	alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'

	# less version 487: 25 oct 2016
	# mark nudelman
	# less@gnu.org via greenwoodsoftware.com
	alias less='less -AFgJMQswX'
	export MANCOLOR=1
	export MANPAGER='less -RAFgJMQswX'
	# Recursively delete `.DS_Store` files
	alias cleanup="find . -name '*.DS_Store' -type f -ls -delete"
fi

if [[ "$OS_TYPE" =~ ^cygwin ]]; then
	alias open="cygstart"
fi

if [[ "$OS_TYPE" =~ ^windows ]]; then
	alias flush='ipconfig /flushdns'
fi

# Print pwd as directory tree
if [ ! -x "$(which tree 2>/dev/null)" ]; then
  alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
fi

# ls variations
alias l.='ls -d .[^.]*'

# Long listing, recent first, -G color
alias l='ls -lhGt'

alias lh="ls -lh"

# Long listing, human readable, no group info
alias ll='ls -lhG'

# Sort with recently modified first
alias lt='ls -lt'

# List only directories
alias lsd='ls -l | grep "^d"'

alias myip='drill +short myip.opendns.com @resolver1.opendns.com'
alias localip='ipconfig getifaddr en1'
#alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias whois='whois -h whois-servers.net'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias cls='clear'
alias path='echo -e ${PATH//:/\\n}'       
alias whence='type -a'

# Go to the last directory CDed from
alias -- -='cd -'
#alias ~ ~='cd ~'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

